"
A CodeChurnOnMergedMergeRequestProjectMetricTest is a test class for testing the behavior of CodeChurnOnMergedMergeRequestProjectMetric
"
Class {
	#name : #CodeChurnOnMergedMergeRequestProjectMetricTest,
	#superclass : #ProjectMetricTest,
	#category : #'GitLabHealth-Model-Analysis-Tests'
}

{ #category : #tests }
CodeChurnOnMergedMergeRequestProjectMetricTest >> testCalculate [

	self flag: #toImplement.
	self assert: false
]
