"
A MergeRequestDurationProjectMetricTest is a test class for testing the behavior of MergeRequestDurationProjectMetric
"
Class {
	#name : #MergeRequestDurationProjectMetricTest,
	#superclass : #TestCase,
	#category : #'GitLabHealth-Model-Analysis-Tests'
}

{ #category : #tests }
MergeRequestDurationProjectMetricTest >> testCalculate [

	self flag: #toImplement.
	self assert: false
]
